### ISSUE TITLE
Module link broken? 

### ISSUE THREAD

**Issue by thortain** [DFreds/dfreds-convenient-effects#248]
**Describe the bug**

Module does not install

1. Click install button on foundry
2. Following error is generated: 

foundry.js:67285 Error: Unable to load valid module manifest data from "https://github.com/DFreds/dfreds-convenient-effects/releases/download/v2.7.3/module.json"
Module validation errors:
  packs: 
    0: 
      type: may not be undefined
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:2076)

**Expected behavior**
Module installs.

**Comment by FurtherV** [comment]
I have the same error on v11. But the module is not updated yet so that might be it?

**Comment by thortain** [comment]
It was the latest version.

**Comment by DFreds** [comment]
Yeah, it's not available for v11 yet
