### ISSUE TITLE
"Cannot read properties of undefined (reading length')" error on load

### ISSUE THREAD

**Issue by thinkedem** [DFreds/dfreds-convenient-effects#329]
### Describe the Bug

Logging in to VTT I get a "Cannot read properties of undefined (reading length')" error message.

### Context

<img width="415" alt="image" src="https://github.com/DFreds/dfreds-convenient-effects/assets/1805343/c3ed7cc6-5927-4343-ac91-eb133e59fad1">

Console error:
```
caught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'length')
[No packages detected]
    at Preprocessor.advance (/Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/node_modules/parse5/dist/tokenizer/preprocessor.js:138:35)
    at Tokenizer._consume (/Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/node_modules/parse5/dist/tokenizer/index.js:270:34)
    at Tokenizer._runParsingLoop (/Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/node_modules/parse5/dist/tokenizer/index.js:221:29)
    at Tokenizer.write (/Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/node_modules/parse5/dist/tokenizer/index.js:248:14)
    at parseFragment (/Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/node_modules/parse5/dist/index.js:42:22)
    at cleanHTML (/Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/dist/database/validators.mjs:1:209)
    at HTMLField.sanitizeHTMLField [as sanitize] (/Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/dist/database/sanitization.mjs:1:1235)
    at Item._sanitizeFields (/Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/dist/database/backend/server-document.mjs:1:7729)
    at Item._sanitizeFields (/Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/dist/database/backend/server-document.mjs:1:7956)
    at Item.sanitizeUserInput (/Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/dist/database/backend/server-document.mjs:1:7436)
```
- I have not run find-the-culprit, but the only modules enabled was this one - even tried with the two "required modules" disabled. Disabling this module makes the error gone.
- Foundry version 11.315
- System D&D 5e 3.2.0
- Module version
  - DFred 6.0.3
  - libWrapper 1.12.13.1 (or disabled)
  - socketlib 1.0.13 (or disabled)
- macOS, game client (no external browser involved)

### To Reproduce

1. Install and enable DFred's Convenient Effects
2. Reload game or logout and login to game again

### Expected Behavior

No error message.

**Comment by DFreds** [comment]
Not sure I've ever seen this, or that it's related to this module. In any case, try again in v7 of CE and make a new issue if it persists
